// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hipolqjthriiwdzfxpdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpcG9scWp0aHJpaXdkemZ4cGRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTYzOTgsImV4cCI6MjA3MzE5MjM5OH0.773yaKin05rXpPrP_-Bfr6i0-i_sy7WNaVT-E_GEzvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});